package com.cybergah.securewipe

/**
 * Uygulamanin butun metinleri tek yerde.
 * Hem Android hem masaustu surumu bu dosyayi kullanir.
 *
 * Ana dil: Kurmanci (KMR) - varsayilan.
 */
enum class Lang(val code: String, val nativeName: String, val rtl: Boolean) {
    KMR("kmr", "Kurmancî", false),
    CKB("ckb", "کوردیی ناوەندی", true),
    AR("ar", "العربية", true),
    TR("tr", "Türkçe", false),
    EN("en", "English", false);

    companion object {
        val DEFAULT = KMR

        fun fromCode(code: String?): Lang =
            entries.firstOrNull { it.code == code } ?: DEFAULT

        /** Sistem dilinden en yakin esleşmeyi bulur, yoksa Kurmanci. */
        fun fromSystem(language: String?, script: String? = null): Lang = when {
            language == null -> DEFAULT
            language.startsWith("ku") && script == "Arab" -> CKB
            language.startsWith("ckb") -> CKB
            language.startsWith("ku") || language.startsWith("kmr") -> KMR
            language.startsWith("ar") -> AR
            language.startsWith("tr") -> TR
            language.startsWith("en") -> EN
            else -> DEFAULT
        }
    }
}

class Strings(
    val appName: String,
    val subtitle: String,        // %1$d
    val pickFiles: String,
    val pickFolder: String,
    val wipeButton: String,
    val clearBtn: String,
    val filesSummary: String,    // %1$d %2$s
    val confirmTitle: String,
    val confirmBody: String,     // %1$d %2$s %3$d
    val confirmWarn: String,
    val confirmYes: String,
    val confirmNo: String,
    val stopBtn: String,
    val bgNote: String,
    val passOf: String,          // %1$d %2$d
    val fileOf: String,          // %1$d %2$d
    val written: String,         // %1$s
    val doneTitle: String,
    val stoppedTitle: String,
    val doneSummary: String,     // %1$d %2$d
    val resDeleted: String,      // %1$d
    val resNotDeleted: String,
    val resStopped: String,
    val resNoWrite: String,
    val notifChannel: String,
    val notifChannelDesc: String,
    val notifRunning: String,
    val notifPreparing: String,
    val notifStop: String,
    val notifDone: String,
    val notifStopped: String,
    val notifFailed: String,     // %1$d
    val notifSummary: String,    // %1$d
    val language: String,
    val emptyFolder: String,
    val about: String,
    val tagline: String,
    val aboutWhat: String,
    val aboutHow: String,
    val step1: String,
    val step2: String,
    val step3: String,
    val step4: String,
    val aboutLimitTitle: String,
    val aboutLimit: String,
    val version: String,
    val close: String,
    val diskEntry: String,
    val diskTitle: String,
    val diskWarn: String,
    val diskRefresh: String,
    val diskSystemLocked: String,
    val diskNone: String,
    val diskButton: String,
    val diskConfirm: String,
    val diskTypeToConfirm: String,
    val diskNeedAdmin: String,
    val diskRestartAdmin: String,
    val diskDone: String,
    val diskFailed: String,
    val diskPreparing: String,
    val diskRemovable: String,
    val diskFixed: String,
    val elapsed: String,
    val remaining: String,
    val calculating: String,
    val diskCancelWarn: String,
    val zeroing: String,
    val theme: String
)

private val KMR = Strings(
    appName = "Bêşop",
    subtitle = "%1\$d caran li ser dinivîse, paşê bi awayekî mayînde jê dibe",
    pickFiles = "Pelan hilbijêre",
    pickFolder = "Peldankê hilbijêre",
    wipeButton = "TUNE BIKE",
    clearBtn = "Paqij bike",
    filesSummary = "%1\$d pel · %2\$s",
    confirmTitle = "Tu piştrast î?",
    confirmBody = "%1\$d pel (%2\$s) dê %3\$d caran li ser bên nivîsandin û bi awayekî mayînde bên jêbirin.",
    confirmWarn = "Ev kar VENAGERE. Pel naçin sergoyê û bi bernameyên vegerandinê jî nayên vegerandin.",
    confirmYes = "JÊ BIBE",
    confirmNo = "Dev jê berde",
    stopBtn = "Rawestîne",
    bgNote = "Kar li paş perdeyê jî berdewam dike.",
    passOf = "derbas %1\$d / %2\$d",
    fileOf = "pel %1\$d / %2\$d",
    written = "%1\$s hate nivîsandin",
    doneTitle = "Qediya",
    stoppedTitle = "Hate rawestandin",
    doneSummary = "%1\$d / %2\$d pel bi awayekî neveger hatin jêbirin",
    resDeleted = "%1\$d derbas hatin nivîsandin, bi awayekî mayînde hate jêbirin",
    resNotDeleted = "Naverok hate tunekirin lê tomara pelê nehate jêbirin",
    resStopped = "Hate rawestandin",
    resNoWrite = "Destûra nivîsandinê nehate wergirtin",
    notifChannel = "Karê jêbirinê",
    notifChannelDesc = "Pêşketina jêbirina ewle",
    notifRunning = "Bêşop dixebite",
    notifPreparing = "Tê amadekirin…",
    notifStop = "Rawestîne",
    notifDone = "Jêbirin qediya",
    notifStopped = "Kar hate rawestandin",
    notifFailed = "Bi %1\$d çewtiyan qediya",
    notifSummary = "%1\$d pel bi awayekî neveger hatin jêbirin",
    language = "Ziman",
    emptyFolder = "Di peldankê de pel nehatin dîtin",
    about = "Der barê",
    tagline = "bêyî şop jê dibe",
    aboutWhat = "Bêşop naveroka pelan bi daneyên tesadufî li ser dinivîse û paşê bi awayekî mayînde jê dibe. Armanc: pelê jêbirî bi bernameyên vegerandinê neyê vegerandin.",
    aboutHow = "Çawa dixebite",
    step1 = "%1\$d caran bi daneyên tesadufî li ser tê nivîsandin (piştî her derbasê fsync)",
    step2 = "Mezinahiya pelê dibe 0 byte",
    step3 = "Pel bi awayekî mayînde tê jêbirin — naçe sergoyê",
    step4 = "Tê pejirandin ku pel bi rastî çûye",
    aboutLimitTitle = "Divê tu zanibî",
    aboutLimit = "Di bîra flash de (eMMC/UFS/SSD) «wear levelling» heye: kontrolker daneyan li bloka kevn nanivîse. Ji ber vê yekê 50 derbas ji 1 derbasî ewletir nîne. Lê li dijî bernameyên vegerandinê ev têrê dike.",
    version = "Guherto %1\$s",
    close = "Bigire",
    diskEntry = "Dîsk",
    diskTitle = "Jêbirina dîskê",
    diskWarn = "HEMÛ dîsk tê jêbirin û ji nû ve tê formatkirin. Her tişt diçe.",
    diskRefresh = "Nû bike",
    diskSystemLocked = "Dîska pergalê — parastî",
    diskNone = "Dîsk nehat dîtin",
    diskButton = "DÎSKÊ JÊ BIBE Û FORMAT BIKE",
    diskConfirm = "%1\$s (%2\$s) dê bi temamî bê jêbirin: her sektor sifir dibe, paşê %3\$d caran bi daneyên tesadufî tê nivîsandin û dîsk ji nû ve tê formatkirin.",
    diskTypeToConfirm = "Ji bo pejirandinê «%1\$s» binivîse",
    diskNeedAdmin = "Destûra rêveberiyê hewce ye",
    diskRestartAdmin = "Wek rêveber ji nû ve dest pê bike",
    diskDone = "Dîsk hat jêbirin û formatkirin",
    diskFailed = "Jêbirin bi ser neket",
    diskPreparing = "Dîsk tê amadekirin…",
    diskRemovable = "Cîhaza derve",
    diskFixed = "Dîska hundir",
    elapsed = "Derbasbûyî %1\$s",
    remaining = "Mayî ~%1\$s",
    calculating = "tê hesibandin…",
    diskCancelWarn = "Eger niha rawestî, dîsk bêformat dimîne û divê ji nû ve bê formatkirin.",
    zeroing = "sifirkirin",
    theme = "Tema"
)

private val CKB = Strings(
    appName = "Bêşop",
    subtitle = "%1\$d جار بەسەریدا دەنووسێتەوە، پاشان بە یەکجاری دەیسڕێتەوە",
    pickFiles = "فایل هەڵبژێرە",
    pickFolder = "بوخچە هەڵبژێرە",
    wipeButton = "لەناوی ببە",
    clearBtn = "پاککردنەوە",
    filesSummary = "%1\$d فایل · %2\$s",
    confirmTitle = "دڵنیایت؟",
    confirmBody = "%1\$d فایل (%2\$s) %3\$d جار بەسەریدا دەنووسرێتەوە و بە یەکجاری دەسڕدرێتەوە.",
    confirmWarn = "ئەم کارە ناگەڕێتەوە. فایلەکان ناچنە تەنەکەی خۆڵ و بە نەرمامێری گەڕاندنەوەش ناگەڕێنەوە.",
    confirmYes = "بیسڕەوە",
    confirmNo = "پاشگەزبوونەوە",
    stopBtn = "ڕاگرتن",
    bgNote = "کارەکە لە پشتەوەش بەردەوام دەبێت.",
    passOf = "جار %1\$d / %2\$d",
    fileOf = "فایل %1\$d / %2\$d",
    written = "%1\$s نووسرا",
    doneTitle = "تەواو بوو",
    stoppedTitle = "ڕاگیرا",
    doneSummary = "%1\$d / %2\$d فایل بە جۆرێک سڕدرانەوە کە ناگەڕێنەوە",
    resDeleted = "%1\$d جار نووسرا، بە یەکجاری سڕدرایەوە",
    resNotDeleted = "ناوەڕۆک لەناوبرا بەڵام تۆماری فایلەکە نەسڕدرایەوە",
    resStopped = "ڕاگیرا",
    resNoWrite = "مۆڵەتی نووسین وەرنەگیرا",
    notifChannel = "کاری سڕینەوە",
    notifChannelDesc = "پێشکەوتنی سڕینەوەی پارێزراو",
    notifRunning = "Bêşop کاردەکات",
    notifPreparing = "ئامادە دەکرێت…",
    notifStop = "ڕاگرتن",
    notifDone = "سڕینەوە تەواو بوو",
    notifStopped = "کارەکە ڕاگیرا",
    notifFailed = "بە %1\$d هەڵە تەواو بوو",
    notifSummary = "%1\$d فایل بە جۆرێک سڕدرانەوە کە ناگەڕێنەوە",
    language = "زمان",
    emptyFolder = "لە بوخچەکەدا هیچ فایلێک نەدۆزرایەوە",
    about = "دەربارە",
    tagline = "بەبێ شوێن دەیسڕێتەوە",
    aboutWhat = "بێشۆپ ناوەڕۆکی فایلەکان بە داتای هەڕەمەکی بەسەریدا دەنووسێتەوە و پاشان بە یەکجاری دەیسڕێتەوە. ئامانج: فایلە سڕدراوەکە بە نەرمامێری گەڕاندنەوە نەگەڕێتەوە.",
    aboutHow = "چۆن کار دەکات",
    step1 = "%1\$d جار بە داتای هەڕەمەکی بەسەریدا دەنووسرێتەوە (دوای هەر جارێک fsync)",
    step2 = "قەبارەی فایلەکە دەکرێتە ٠ بایت",
    step3 = "فایلەکە بە یەکجاری دەسڕدرێتەوە — ناچێتە تەنەکەی خۆڵ",
    step4 = "پشتڕاست دەکرێتەوە کە بەڕاستی نەماوە",
    aboutLimitTitle = "دەبێت بزانیت",
    aboutLimit = "لە بیرگەی فلاشدا (eMMC/UFS/SSD) «wear levelling» هەیە: کۆنترۆڵەر داتاکە لە بلۆکی کۆن نانووسێتەوە. بۆیە ٥٠ جار لە ١ جار پارێزراوتر نییە. بەڵام بەرامبەر نەرمامێری گەڕاندنەوە ئەمە بەسە.",
    version = "وەشانی %1\$s",
    close = "داخستن",
    diskEntry = "دیسک",
    diskTitle = "سڕینەوەی دیسک",
    diskWarn = "هەموو دیسکەکە دەسڕدرێتەوە و دووبارە فۆرمات دەکرێت. هەموو شتێک لەناودەچێت.",
    diskRefresh = "نوێکردنەوە",
    diskSystemLocked = "دیسکی سیستەم — پارێزراو",
    diskNone = "هیچ دیسکێک نەدۆزرایەوە",
    diskButton = "دیسک بسڕەوە و فۆرمات بکە",
    diskConfirm = "%1\$s (%2\$s) بە تەواوی دەسڕدرێتەوە: هەموو سێکتەرێک سفر دەکرێت، پاشان %3\$d جار بە داتای هەڕەمەکی دەنووسرێتەوە و دیسکەکە دووبارە فۆرمات دەکرێت.",
    diskTypeToConfirm = "بۆ پشتڕاستکردنەوە «%1\$s» بنووسە",
    diskNeedAdmin = "مۆڵەتی بەڕێوەبەر پێویستە",
    diskRestartAdmin = "وەک بەڕێوەبەر دووبارە دەستپێبکە",
    diskDone = "دیسک سڕدرایەوە و فۆرمات کرا",
    diskFailed = "سڕینەوە سەرکەوتوو نەبوو",
    diskPreparing = "دیسک ئامادە دەکرێت…",
    diskRemovable = "ئامێری دەرەکی",
    diskFixed = "دیسکی ناوەکی",
    elapsed = "تێپەڕیو %1\$s",
    remaining = "ماوە ~%1\$s",
    calculating = "دەخەملێنرێت…",
    diskCancelWarn = "ئەگەر ئێستا ڕایبگریت، دیسکەکە بێ فۆرمات دەمێنێتەوە و دەبێت دووبارە فۆرمات بکرێت.",
    zeroing = "سفرکردن",
    theme = "ڕووکار"
)

private val AR = Strings(
    appName = "Bêşop",
    subtitle = "يكتب فوقه %1\$d مرة ثم يحذفه نهائيًا",
    pickFiles = "اختر ملفات",
    pickFolder = "اختر مجلدًا",
    wipeButton = "أبِدْه",
    clearBtn = "مسح القائمة",
    filesSummary = "%1\$d ملف · %2\$s",
    confirmTitle = "هل أنت متأكد؟",
    confirmBody = "سيتم الكتابة فوق %1\$d ملف (%2\$s) %3\$d مرة ثم حذفه نهائيًا.",
    confirmWarn = "لا يمكن التراجع عن هذه العملية. لن تذهب الملفات إلى سلة المهملات ولا يمكن استرجاعها ببرامج الاستعادة.",
    confirmYes = "احذف",
    confirmNo = "إلغاء",
    stopBtn = "إيقاف",
    bgNote = "تستمر العملية في الخلفية أيضًا.",
    passOf = "المرور %1\$d / %2\$d",
    fileOf = "ملف %1\$d / %2\$d",
    written = "تمت كتابة %1\$s",
    doneTitle = "اكتمل",
    stoppedTitle = "أُوقفت",
    doneSummary = "تم محو %1\$d / %2\$d ملف دون إمكانية الاسترجاع",
    resDeleted = "تمت الكتابة %1\$d مرة، وحُذف نهائيًا",
    resNotDeleted = "أُتلف المحتوى لكن تعذّر حذف سجل الملف",
    resStopped = "أُوقفت",
    resNoWrite = "تعذّر الحصول على إذن الكتابة",
    notifChannel = "عملية المحو",
    notifChannelDesc = "تقدّم المحو الآمن",
    notifRunning = "Bêşop قيد التشغيل",
    notifPreparing = "جارٍ التحضير…",
    notifStop = "إيقاف",
    notifDone = "اكتمل المحو",
    notifStopped = "أُوقفت العملية",
    notifFailed = "انتهى مع %1\$d من الأخطاء",
    notifSummary = "تم محو %1\$d ملف دون إمكانية الاسترجاع",
    language = "اللغة",
    emptyFolder = "لم يُعثر على ملفات في المجلد",
    about = "حول",
    tagline = "يمحو دون أن يترك أثرًا",
    aboutWhat = "يكتب Bêşop بيانات عشوائية فوق محتوى الملفات ثم يحذفها نهائيًا. الهدف: ألا تتمكن برامج الاستعادة من إرجاع الملف المحذوف.",
    aboutHow = "كيف يعمل",
    step1 = "يكتب فوق المحتوى %1\$d مرة ببيانات عشوائية (مع fsync بعد كل مرة)",
    step2 = "يجعل حجم الملف صفر بايت",
    step3 = "يحذف الملف نهائيًا — لا يذهب إلى سلة المهملات",
    step4 = "يتحقق من أن الملف اختفى فعلًا",
    aboutLimitTitle = "ما يجب معرفته",
    aboutLimit = "في ذاكرة الفلاش (eMMC/UFS/SSD) يوجد «توزيع التآكل»: المتحكم لا يكتب البيانات في الكتلة القديمة. لذلك ٥٠ مرة ليست أأمن من مرة واحدة. لكنها كافية ضد برامج الاستعادة.",
    version = "الإصدار %1\$s",
    close = "إغلاق",
    diskEntry = "القرص",
    diskTitle = "محو القرص",
    diskWarn = "سيُمحى القرص بالكامل ويُعاد تهيئته. كل شيء عليه سيضيع.",
    diskRefresh = "تحديث",
    diskSystemLocked = "قرص النظام — محمي",
    diskNone = "لم يُعثر على أقراص",
    diskButton = "امحُ القرص وأعد تهيئته",
    diskConfirm = "سيُمحى %1\$s (%2\$s) بالكامل: تُصفَّر كل القطاعات، ثم يُكتب فوقها %3\$d مرات ببيانات عشوائية ويُعاد تهيئة القرص.",
    diskTypeToConfirm = "اكتب «%1\$s» للتأكيد",
    diskNeedAdmin = "مطلوب صلاحية المسؤول",
    diskRestartAdmin = "أعد التشغيل كمسؤول",
    diskDone = "تم محو القرص وإعادة تهيئته",
    diskFailed = "فشل المحو",
    diskPreparing = "يجري تحضير القرص…",
    diskRemovable = "جهاز خارجي",
    diskFixed = "قرص داخلي",
    elapsed = "المنقضي %1\$s",
    remaining = "المتبقي ~%1\$s",
    calculating = "يجري الحساب…",
    diskCancelWarn = "إذا أوقفت الآن سيبقى القرص بلا تهيئة وسيلزم إعادة تهيئته.",
    zeroing = "التصفير",
    theme = "المظهر"
)

private val TR = Strings(
    appName = "Bêşop",
    subtitle = "%1\$d kez üzerine yazar, sonra kalıcı siler",
    pickFiles = "Dosya seç",
    pickFolder = "Klasör seç",
    wipeButton = "YOK ET",
    clearBtn = "Temizle",
    filesSummary = "%1\$d dosya · %2\$s",
    confirmTitle = "Emin misin?",
    confirmBody = "%1\$d dosya (%2\$s) %3\$d kez üzerine yazılıp kalıcı olarak silinecek.",
    confirmWarn = "Bu işlem GERİ ALINAMAZ. Dosyalar çöp kutusuna gitmez, kurtarma yazılımlarıyla da geri getirilemez.",
    confirmYes = "SİL",
    confirmNo = "Vazgeç",
    stopBtn = "Durdur",
    bgNote = "İşlem arka planda da sürer.",
    passOf = "geçiş %1\$d / %2\$d",
    fileOf = "dosya %1\$d / %2\$d",
    written = "%1\$s yazıldı",
    doneTitle = "Tamamlandı",
    stoppedTitle = "Durduruldu",
    doneSummary = "%1\$d / %2\$d dosya geri getirilemez şekilde silindi",
    resDeleted = "%1\$d geçiş yazıldı, kalıcı silindi",
    resNotDeleted = "İçerik yok edildi ama dosya kaydı silinemedi",
    resStopped = "Durduruldu",
    resNoWrite = "Yazma izni alınamadı",
    notifChannel = "Silme işlemi",
    notifChannelDesc = "Güvenli silme ilerlemesi",
    notifRunning = "Bêşop çalışıyor",
    notifPreparing = "Hazırlanıyor…",
    notifStop = "Durdur",
    notifDone = "Silme tamamlandı",
    notifStopped = "İşlem durduruldu",
    notifFailed = "Silme bitti (%1\$d hata)",
    notifSummary = "%1\$d dosya geri getirilemez şekilde silindi",
    language = "Dil",
    emptyFolder = "Klasörde dosya bulunamadı",
    about = "Hakkında",
    tagline = "iz bırakmadan siler",
    aboutWhat = "Bêşop, dosyaların içeriğinin üzerine rastgele veri yazar ve sonra kalıcı olarak siler. Amaç: silinen dosyanın kurtarma yazılımlarıyla geri getirilememesi.",
    aboutHow = "Nasıl çalışır",
    step1 = "İçeriğin üzerine %1\$d kez rastgele veri yazılır (her geçişten sonra fsync)",
    step2 = "Dosya 0 byte'a indirilir",
    step3 = "Dosya kalıcı olarak silinir — çöp kutusuna gitmez",
    step4 = "Dosyanın gerçekten gittiği doğrulanır",
    aboutLimitTitle = "Bilinmesi gereken",
    aboutLimit = "Flash bellekte (eMMC/UFS/SSD) aşınma dengeleme vardır: denetleyici veriyi eski fiziksel bloğa yazmaz. Bu yüzden 50 geçiş, 1 geçişten daha güvenli değildir. Ama kurtarma yazılımlarına karşı bu yeterlidir.",
    version = "Sürüm %1\$s",
    close = "Kapat",
    diskEntry = "Disk",
    diskTitle = "Disk silme",
    diskWarn = "Diskin TAMAMI silinir ve yeniden biçimlendirilir. Üzerindeki her şey gider.",
    diskRefresh = "Yenile",
    diskSystemLocked = "Sistem diski — korumalı",
    diskNone = "Disk bulunamadı",
    diskButton = "DİSKİ SİL VE BİÇİMLENDİR",
    diskConfirm = "%1\$s (%2\$s) tamamen silinecek: her sektör sıfırlanır, sonra %3\$d kez rastgele veriyle üzerine yazılır ve disk yeniden biçimlendirilir.",
    diskTypeToConfirm = "Onaylamak için «%1\$s» yaz",
    diskNeedAdmin = "Yönetici yetkisi gerekiyor",
    diskRestartAdmin = "Yönetici olarak yeniden başlat",
    diskDone = "Disk silindi ve biçimlendirildi",
    diskFailed = "Silme başarısız oldu",
    diskPreparing = "Disk hazırlanıyor…",
    diskRemovable = "Çıkarılabilir",
    diskFixed = "Sabit disk",
    elapsed = "Geçen %1\$s",
    remaining = "Kalan ~%1\$s",
    calculating = "hesaplanıyor…",
    diskCancelWarn = "Şimdi durdurursan disk biçimsiz kalır ve yeniden biçimlendirmen gerekir.",
    zeroing = "sıfırlama",
    theme = "Tema"
)

private val EN = Strings(
    appName = "Bêşop",
    subtitle = "Overwrites %1\$d times, then deletes permanently",
    pickFiles = "Choose files",
    pickFolder = "Choose folder",
    wipeButton = "DESTROY",
    clearBtn = "Clear",
    filesSummary = "%1\$d files · %2\$s",
    confirmTitle = "Are you sure?",
    confirmBody = "%1\$d file(s) (%2\$s) will be overwritten %3\$d times and then permanently deleted.",
    confirmWarn = "This CANNOT BE UNDONE. Files do not go to the trash and cannot be brought back by recovery software.",
    confirmYes = "ERASE",
    confirmNo = "Cancel",
    stopBtn = "Stop",
    bgNote = "The job keeps running in the background.",
    passOf = "pass %1\$d / %2\$d",
    fileOf = "file %1\$d / %2\$d",
    written = "%1\$s written",
    doneTitle = "Done",
    stoppedTitle = "Stopped",
    doneSummary = "%1\$d / %2\$d files erased beyond recovery",
    resDeleted = "%1\$d passes written, permanently deleted",
    resNotDeleted = "Contents destroyed but the file entry could not be deleted",
    resStopped = "Stopped",
    resNoWrite = "Could not get write access",
    notifChannel = "Erase job",
    notifChannelDesc = "Secure erase progress",
    notifRunning = "Bêşop is running",
    notifPreparing = "Preparing…",
    notifStop = "Stop",
    notifDone = "Erase complete",
    notifStopped = "Job stopped",
    notifFailed = "Finished with %1\$d error(s)",
    notifSummary = "%1\$d files erased beyond recovery",
    language = "Language",
    emptyFolder = "No files found in the folder",
    about = "About",
    tagline = "erases without a trace",
    aboutWhat = "Bêşop overwrites file contents with random data and then deletes them permanently. The goal: recovery software cannot bring the deleted file back.",
    aboutHow = "How it works",
    step1 = "Contents overwritten %1\$d times with random data (fsync after each pass)",
    step2 = "File truncated to 0 bytes",
    step3 = "File deleted permanently — it does not go to the trash",
    step4 = "Deletion is verified",
    aboutLimitTitle = "What you should know",
    aboutLimit = "Flash memory (eMMC/UFS/SSD) uses wear levelling: the controller does not write to the old physical block. So 50 passes are no safer than 1. Against recovery software, however, this is enough.",
    version = "Version %1\$s",
    close = "Close",
    diskEntry = "Disk",
    diskTitle = "Disk wipe",
    diskWarn = "The ENTIRE disk is erased and reformatted. Everything on it is lost.",
    diskRefresh = "Refresh",
    diskSystemLocked = "System disk — protected",
    diskNone = "No disks found",
    diskButton = "ERASE AND FORMAT DISK",
    diskConfirm = "%1\$s (%2\$s) will be completely erased: every sector is zeroed, then overwritten %3\$d times with random data, and the disk is reformatted.",
    diskTypeToConfirm = "Type «%1\$s» to confirm",
    diskNeedAdmin = "Administrator rights required",
    diskRestartAdmin = "Restart as administrator",
    diskDone = "Disk erased and reformatted",
    diskFailed = "Erase failed",
    diskPreparing = "Preparing disk…",
    diskRemovable = "Removable",
    diskFixed = "Fixed disk",
    elapsed = "Elapsed %1\$s",
    remaining = "Remaining ~%1\$s",
    calculating = "calculating…",
    diskCancelWarn = "If you stop now the disk is left unformatted and must be reformatted.",
    zeroing = "zeroing",
    theme = "Theme"
)

fun stringsFor(lang: Lang): Strings = when (lang) {
    Lang.KMR -> KMR
    Lang.CKB -> CKB
    Lang.AR -> AR
    Lang.TR -> TR
    Lang.EN -> EN
}
